language: php
php:
  - 5.4
  - 5.5

before_script:
  - git clone git://github.com/squizlabs/PHP_CodeSniffer.git
  - psql -c "DROP DATABASE IF EXISTS strayFw_test;" -U postgres
  - psql -c "CREATE DATABASE strayFw_test;" -U postgres
  - sh -c "cp quality/settings.tests.yml settings.yml"

script: sh quality/quality.sh
