language: php
php:
  - 5.4
  - 5.5

before_script:
  - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar
  - psql -c "DROP DATABASE IF EXISTS strayFw_test;" -U postgres
  - psql -c "CREATE DATABASE strayFw_test;" -U postgres
  - sh -c "cp quality/settings.tests.yml settings.yml"

script: sh quality/quality.sh
