language: php
php:
  - 7.1

before_script:
  - psql -c "DROP DATABASE IF EXISTS strayFw_test;" -U postgres
  - psql -c "CREATE DATABASE strayFw_test;" -U postgres
  - sh -c "cp quality/settings.tests.yml settings.yml"
  - composer install

script: phpunit --configuration quality/phpunit_pgsql.xml --coverage-text
