tmp: /tmp/stray
domainprefix:

plugins:
  -

databases:
  global:
    host: localhost
    port:
    name: errant_global
    user: errant
    pass:
  lostsouls:
    write:
      host: localhost
      port:
      name: errant_global
      user: errant
      pass:
    read:
      -
        host: localhost
        port:
        name: errant_global
        user: errant
        pass:
      -
        host: localhost
        port:
        name: errant_global
        user: errant
        pass:

i18n:
  default: en
  hosts:
    example.com: en
    exemple.fr: fr
