tmp: tmp
domainprefix:

plugins:
  -

databases:
  global:
    host: localhost
    port:
    name: postgres
    user: postgres
    pass:

mongo:
  host: localhost
  db_prefix: stray_

i18n:
  default: en
  hosts:
    example.com: en
  locales:
    en: en_US
